# Used as guide:
# https://www.r-bloggers.com/how-to-perform-a-logistic-regression-in-r/

library(pscl)
library(ROCR)

# All column names without defects
allColumns <- c("loc", "v(g)", "ev(g)", "iv(g)", "n", "v", "l", "d", "i", "e", "b", "t", "lOCode", "lOComment", "lOBlank", "LocCodeAndComment", "uniq_Op", "uniq_Opnd", "total_Op", "total_Opnd", "branchCount")
#str = "iv(g)"

for (str in allColumns) {
  data = processedData[c(str, "defects")]
  data = data[order(data[, str]),c(1,2)]
  #data = processedData
  train <- data[1:8000,]
  test <- data[8001:10880,]
  
  model <- glm(defects ~.,family=binomial(link='logit'),data=train)
  
  anova(model, test="Chisq")
  pR2(model)
  
  p <- predict(model, newdata=subset(test,select=str), type="response")
  pr <- prediction(p, test$defects)
  prf <- performance(pr, measure = "tpr", x.measure = "fpr")
  plot(prf)
  
  # The ROC is a curve generated by plotting the true positive rate (TPR)
  # against the false positive rate (FPR) at various threshold settings
  # while the AUC is the area under the ROC curve.
  # As a rule of thumb, a model with good predictive ability
  # should have an AUC closer to 1 (1 is ideal) than to 0.5.
  
  auc <- performance(pr, measure = "auc")
  auc <- auc@y.values[[1]]
  print(str)
  print(auc)
  print("---")
}